### ISSUE TITLE
Bug with EchoPet

### ISSUE THREAD

**Issue by Greenman1805** [Nicewuerfel/BlockOwn#146]
I've installed the plugin EchoPet and everytime a user switches the world I get this error:

[19:37:04 ERROR]: Could not pass event EntityDamageEvent to BlockOwn v3.3.4
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:553) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:539) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:585) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1102) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:743) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.EntityLiving.e(EntityLiving.java:939) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.Block.fallOn(Block.java:640) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.Entity.a(Entity.java:811) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.EntityLiving.a(EntityLiving.java:160) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.Entity.move(Entity.java:627) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.EntityLiving.g(EntityLiving.java:1395) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at com.dsh105.echopet.compat.nms.v1_8_R3.entity.EntityPet.g(EntityPet.java:351) [EchoPet_v2.8.0.jar:?]
        at net.minecraft.server.v1_8_R3.EntityLiving.m(EntityLiving.java:1652) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.EntityInsentient.m(EntityInsentient.java:338) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1487) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.EntityInsentient.t_(EntityInsentient.java:193) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at com.dsh105.echopet.compat.nms.v1_8_R3.entity.EntityPet.t_(EntityPet.java:450) [EchoPet_v2.8.0.jar:?]
        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
        at java.lang.Class.isAssignableFrom(Native Method) ~[?:1.8.0_66]
        at de.pheasn.blockown.BlockOwn.isOwnEnabled(BlockOwn.java:277) ~[?:?]
        at de.pheasn.blockown.event.L_EnvironmentDamage.invalidAccess(L_EnvironmentDamage.java:198) ~[?:?]
        at de.pheasn.blockown.event.L_EnvironmentDamage.onEntityDamage(L_EnvironmentDamage.java:114) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
        ... 30 more

**Comment by Nicewuerfel** [comment]
It would be nice if you could try to reproduce the issue with BlockOwn 5.0-BETA.
You can download it here: https://s3.amazonaws.com/pheasn-travis/Nicewuerfel/BlockOwn/44/44.1/target/blockown-5.0.jar

**Comment by Greenman1805** [comment]
I was able to reproduce it:
http://pastebin.com/DaGNri2J

**Comment by Nicewuerfel** [comment]
Does this version fix the issue for you? https://pheasn-travis.s3.amazonaws.com/Nicewuerfel/BlockOwn/48/48.1/target/blockown-5.0.1-SNAPSHOT.jar

**Comment by Greenman1805** [comment]
Yes, no errors anymore! :)

**Comment by Nicewuerfel** [comment]
Nice! Thank you for your bug report, glad I could help :)
